apiVersion: apps/v1
kind: Deployment
metadata:
  name: beamvr-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beamvr
  template:
    metadata:
      labels:
        app: beamvr
    spec:
      containers:
        - name: beamvr-app
          image: nginx:latest
          ports:
            - containerPort: 443
