apiVersion: apps/v1
kind: Deployment
metadata:
  name: beamvr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beamvr-app
  template:
    metadata:
      labels:
        app: beamvr-app
    spec:
      containers:
        - name: beamvr-app
          image: nginx:latest
          ports:
            - containerPort: 80